### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by CurrentlyHidden**
YashDk sucks and is to be removed

### CODE REVIEW

**Comment by dishapatel010** [comment]
> YashDk sucks and is to be removed

Haha 😂 u you peru with nothing still using its repo for leeching & saying what he did to u lol shameful

**Comment by CurrentlyHidden** [comment]
> > YashDk sucks and is to be removed
> 
> Haha 😂 u you peru with nothing still using its repo for leeching & saying what he did to u lol shameful

this is our repo go hoe dickhead😂😂

**Comment by CurrentlyHidden** [comment]
@reaitten  we need to remove some people From this repo asap

ban the following
@dishapatel010

**Comment by CurrentlyHidden** [comment]
> > YashDk sucks and is to be removed
> 
> Haha 😂 u you peru with nothing still using its repo for leeching & saying what he did to u lol shameful

Shut Up Indian Madarchod Leecher LOL i request everyone to look the repositories of @dishapatel010  and he  kangs and rapes heroku  LOL completely shameless dickheads exposed openly 😂😂😂

**Comment by CurrentlyHidden** [comment]
@reaitten we need to change the repo name Or archive It Because of this Fuckers

**Comment by reaitten** [comment]
> @reaitten we need to change the repo name Or archive It Because of this Fuckers

ok what should i rename it to

**Comment by AmirulAndalib** [comment]
**@reaitten**  clean dis mess

**Pull request closed without merging**
